name: Update Basketball Calendars

on:
  push:
    branches:
      - main
  schedule:
    # Run daily at 06:00 UTC (08:00 Athens time)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-calendars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker compose build

    - name: Generate calendars
      run: docker compose up

    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: basketball-calendars
        path: ./output
        retention-days: 1

  deploy-pages:
    needs: update-calendars
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: basketball-calendars
        path: ./output

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './output'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
